### ISSUE TITLE
when can I activate adb

### ISSUE THREAD

**Issue by zhanglihow** [ricohapi/theta-plugin-sdk#5]
https://api.ricoh/docs/theta-plugin/how-to-develop/
about 'How to Develop' 
When can I activate adb?

**Comment by shohara** [comment]
Developers who want to activate adb need to be registered from below URL.
https://www8.webcas.net/db/pub/ricoh/thetaplugin/create/input

Please refer ["How to join the partner program"](https://api.ricoh/products/theta-plugin/) in detail.
